//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seller()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int seller_id { get; set; }
        public string seller_name { get; set; }
        public int city_id { get; set; }
        public string AspUser { get; set; }
        public string address { get; set; }
        public string phone_number { get; set; }
        public System.DateTime join_date { get; set; }
        public string ID_photo { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<bool> Accept { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
